dist:     trusty
sudo:     required

language: c

os:
  - linux

compiler:
  - gcc

addons:
  apt:
    packages:
     - valgrind
     # - cppcheck
     # - make
     # - cmake


# env:
#   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug
#   - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release
#   - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
#   - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

matrix:
  exclude:
    - os:       osx
      compiler: gcc

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

    - os:  osx
      env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release


script:
  - make clean && make
  - ./tests.out
